// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3EBqxLtIg6hAG32bFBZ6-bKGEGvZ3nbU',
    appId: '1:10755659466:web:71400363514a2a37344633',
    messagingSenderId: '10755659466',
    projectId: 'funnychat-9d7db',
    authDomain: 'funnychat-9d7db.firebaseapp.com',
    storageBucket: 'funnychat-9d7db.appspot.com',
    measurementId: 'G-94N2NG74NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGWAXy6gHXQA1LQIu3tOoOTeCmfNHivcU',
    appId: '1:10755659466:android:8af58df30cad0482344633',
    messagingSenderId: '10755659466',
    projectId: 'funnychat-9d7db',
    storageBucket: 'funnychat-9d7db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOdPNSiJhIRHopy4vkwQWp9DS0OsWgbdk',
    appId: '1:10755659466:ios:80d6c4ff6478695f344633',
    messagingSenderId: '10755659466',
    projectId: 'funnychat-9d7db',
    storageBucket: 'funnychat-9d7db.appspot.com',
    iosBundleId: 'com.funnychat.funnyChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOdPNSiJhIRHopy4vkwQWp9DS0OsWgbdk',
    appId: '1:10755659466:ios:80d6c4ff6478695f344633',
    messagingSenderId: '10755659466',
    projectId: 'funnychat-9d7db',
    storageBucket: 'funnychat-9d7db.appspot.com',
    iosBundleId: 'com.funnychat.funnyChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3EBqxLtIg6hAG32bFBZ6-bKGEGvZ3nbU',
    appId: '1:10755659466:web:8e04a9d0b2a809b3344633',
    messagingSenderId: '10755659466',
    projectId: 'funnychat-9d7db',
    authDomain: 'funnychat-9d7db.firebaseapp.com',
    storageBucket: 'funnychat-9d7db.appspot.com',
    measurementId: 'G-PMEJ6QVYY7',
  );
}
